name: Marc-Andre Giroux's Blog
description: Tails about code, music, and stuffs
meta_description: "Marc-Andre Giroux personal blog about rails, react, relay and more"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://mgiroux.me'
google_analytics: 'UA-69973242-1'
disqus: true
disqus_shortname: 'marcandregirouxblog'

# Details for the RSS feed generator
url:            'http://mgiroux.me'
author:         'Marc-Andre Giroux'
authorTwitter:  '__xuorig__'
authorGoogle: 'https://plus.google.com/103412889445491341044'

permalink:       /:year/:title/

gems:
  - jekyll-sitemap

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
